# Site settings
title: Dylan Glenister | Portfolio
description: This is my portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dylan Glenister
user_title: Software Developer
user_description: I enjoy making and playing games
email: dylanglenister@outlook.com
twitter_username: TOSlenderFox
github_username:  SlenderFox

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
